### ISSUE TITLE
Mods don't have their messages shown

### ISSUE THREAD

**Issue by Hejsil** [kristoff-it/bork#3]
This is probably because the parser is not taking something into account:
![image](https://user-images.githubusercontent.com/3759175/103232616-d115ee80-4932-11eb-984d-273c6ea12b8e.png)

**Comment by kristoff-it** [comment]
Can you paste one of those messages from `bork.log`?

**Comment by Hejsil** [comment]
```
[debug] (default): unknown: @badge-info=founder/2;badges=moderator/1,founder/0,premium/1;
client-nonce=fbe59befcb1a315845379957d8753aec;color=#006880;display-name=kcthepandaman;
emotes=;flags=;id=38dec4d8-19e7-479d-8120-0b3ec4af5987;mod=1;room-id=23875822;
subscriber=0;tmi-sent-ts=1609176796155;turbo=0;user-id=25174982;user-type=mod 
:kcthepandaman!kcthepandaman@kcthepandaman.tmi.twitch.tv PRIVMSG #komarispaghetti :We are not here
```

**Comment by kristoff-it** [comment]
Docs not exactly up to date I see
![image](https://user-images.githubusercontent.com/1950733/103234044-f4df3180-493e-11eb-9b33-706a15535296.png)

**Comment by kristoff-it** [comment]
So founder is the special type of subscriber, like the first 10 IIRC? Also `user-type=mod` allows detecting mods.

Do you want to do the fix or shall I do it?

**Comment by Hejsil** [comment]
Well, I'm probably not gonna get around to it today, so you can jump on it
